import {Dimensions, Platform} from "react-native";

export const ThemeConstants = {
    colors: {
        white: '#ffffff',
        black: '#000000',
        grey0: '#393e42',
        grey1: '#43484d',
        grey2: '#5e6977',
        grey3: '#86939e',
        grey4: '#bdc6cf',
        grey5: '#e1e8ee',
        grey6: '#979797',
        grey7: '#ECECEC',
        grey8: '#E9E9E9',
        blue: '#2E79F7',
        background: "#F2F2F2",
        darkBlue: '#2F408B',
        lightblue: '#e7f1fe',
        lightgreen: '#a2cc6e',
        red: '#E03B24',
        yellow: '#ffff00',
        green: '#3CD278',
        transparent: '#00000000',
        orange: '#ff8040',
        buttonColor: '#2C1F47',
        secondaryColor: "#2C1F47",
        navigationColor: '#EBEBEB',
        primaryTextColor: "#000000",
        secondaryTextColor: "#585858",
        chipColor: "#ECECEC",
        segmentTabColor: "#F9DBCB",
        purple: "#2C1F47",
        rowRecord: "#43385B",
        rowCount: "#342C47",
        surface: 'rgba(240, 240, 245, 1)',
        blue0: '#3f56cd',
        line: '#E7E7F4',
        shopbranding: 'rgba(220, 60, 75, 1)',
        shopblue: '#4169E1',
        shopgrey: 'gray',
        chipBlue: "#E5EEFF",
        chipBlueText: "#0056FB",
        chipRed: "#FEEAEB",
        chipRedText: "#F0323C",
        chipYellow: "#FFF0C4",
        chipYellowText: "#D98b16",
        chipGreen: "#D8F6E4",
        chipGreenText: "#3CD278",
        semiBoldColor: "#313131",
        unFinishedIndicator: '#A6A6A6',
        unFinishedLabel: '#6B6B6B',
        leaveDeepPurple: '#5e35b1',
        leaveGrey: '#757575',
        leaveYellow: '#fdd835',
        leaveIndigo: '#3949ab',
        leaveDeepOrange: '#f4511e',
        leaveGreen: '#43a047',
        invoiceRed: '#ff4641',
        chipOrange: '#ffefd5',
        demoColor: "#9769f8",
        appBgColor: "#F2F2F2",
        demoText: "#d6c5fd",
        dashboardLabel: "#E5EFFF",
        chatDateBGColor: '#e0dede',
        subBg:"#131933",
        transparentGray:'rgba(99,98,98,0.53)',
    },
    dimension: {
        border: {
            tiny: 2,
            small: 4,
            normal: 8,
            medium: 12,
            large: 16,
            extraMedium: 24,
            extraLarge: 40
        },
        window: {
            width: Dimensions.get('window').width,
            height: Dimensions.get('window').height
        },
        none: 0,
        horizontalSmall: 8,
        horizontalExtraSmall: 4,
        horizontalDefault: 16,
        horizontalMedium: 24,
        horizontalLarge: 32,
        verticalDefault: 12,
        verticalLarge: 16,
        verticalMedium: 24,
        verticalExtraLarge: 32,
        verticalDefaultSmall: 10,
        verticalExtraSmall: 4,
        verticalSmall: 8,
        padding: 8,
        actionIconSmall: 24,
        cardBottom: 30,
        actionIconDefault: 32,
        avatar: 40,
        avatarMedium: 48,
        avatarLarge: 60,
        clickArea: 4,
        elevation: 4,
        dividerHeight: 0.8,
        headerHeight: 100,
        chartHeight: 150,
        introHeight: 160,
        optionModalHeight: 300,
        dropdownItemHeight: 200
    },
    fontSizes: {
        header: Platform.OS === 'ios' ? 42 : 40,
        large: Platform.OS === 'ios' ? 24 : 20,
        mediumLarge: Platform.OS === 'ios' ? 28 : 22,
        extraLarge: Platform.OS === 'ios' ? 32 : 30,
        regular: Platform.OS === 'ios' ? 18 : 16,
        extraMedium: Platform.OS === 'ios' ? 20 : 18,
        medium: Platform.OS === 'ios' ? 16 : 16,
        small: Platform.OS === 'ios' ? 14 : 14,
        mediumSmall: Platform.OS === 'ios' ? 12 : 12,
        extraSmall: Platform.OS === 'ios' ? 10 : 10,
        navigation: 35,
        sectionHeader: 20,
    },
    other: {
        actionOpacityDefault: 0.5
    }
}
